.TH "Basics.SortByX" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Basics.SortByX \- Sort algorithm for position by the x coordinate\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Comparator< Position >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBcompare\fP (\fBPosition\fP a, \fBPosition\fP b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Sort algorithm for position by the x coordinate\&. 


.PP
\fBAuthor\fP
.RS 4
gabriel 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "int Basics\&.SortByX\&.compare (\fBPosition\fP a, \fBPosition\fP b)"
Compare two positions\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP On position\&. 
.br
\fIb\fP The other position\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The difference between positions\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
