.TH "Basics.SortByX" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Basics.SortByX
.SH SYNOPSIS
.br
.PP
.PP
Inherits Comparator< Position >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBcompare\fP (\fBPosition\fP a, \fBPosition\fP b)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
gabriel 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
