.TH "Model.Individuals.Tiles.BuildingTile" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Model.Individuals.Tiles.BuildingTile
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBModel\&.Individuals\&.Tiles\&.Tile\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBuildingTile\fP (int nCitycents)"
.br
.ti -1c
.RI "\fBBuildingTile\fP \fBmakeCopy\fP ()"
.br
.ti -1c
.RI "int \fBgetCITIZENS\fP ()"
.br
.ti -1c
.RI "int \fBgetValue\fP (\fBTileType\fP type)"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBModel\&.Individuals\&.Tiles\&.Tile\fP
.in +1c
.ti -1c
.RI "int \fBgetValue\fP ()"
.br
.ti -1c
.RI "boolean \fBisVoid\fP ()"
.br
.ti -1c
.RI "boolean \fBisBuilding\fP ()"
.br
.ti -1c
.RI "boolean \fBisPark\fP ()"
.br
.ti -1c
.RI "boolean \fBisRoad\fP ()"
.br
.ti -1c
.RI "boolean \fBcanBuild\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final int \fBMAXCITIZEN\fP = 100"
.br
.ti -1c
.RI "static final int \fBMINCITIZEN\fP = 5"
.br
.in -1c

Static Public Attributes inherited from \fBModel\&.Individuals\&.Tiles\&.Tile\fP
.in +1c
.ti -1c
.RI "static int \fBNOVALUETILE\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
gabriel 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBBuildingTile\fP Model\&.Individuals\&.Tiles\&.BuildingTile\&.makeCopy ()"

.PP
Reimplemented from \fBModel\&.Individuals\&.Tiles\&.Tile\fP\&.
.SS "int Model\&.Individuals\&.Tiles\&.BuildingTile\&.getValue (\fBTileType\fP type)"

.PP
Reimplemented from \fBModel\&.Individuals\&.Tiles\&.Tile\fP\&.
.SS "String Model\&.Individuals\&.Tiles\&.BuildingTile\&.toString ()"

.PP
Reimplemented from \fBModel\&.Individuals\&.Tiles\&.Tile\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
