.TH "Model.ModelParameters" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Model.ModelParameters
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBModelParameters\fP (int popSize, int moneyPond)"
.br
.ti -1c
.RI "int \fBgetPOPULATIONSIZE\fP ()"
.br
.ti -1c
.RI "int \fBgetMONEYPONDERATION\fP ()"
.br
.ti -1c
.RI "double \fBgetCROSSOVERPROB\fP ()"
.br
.ti -1c
.RI "int \fBgetCROSSOVERINTENSITY\fP ()"
.br
.ti -1c
.RI "boolean \fBgetUSEELITISM\fP ()"
.br
.ti -1c
.RI "boolean \fBgetUSETRUNCATE\fP ()"
.br
.ti -1c
.RI "double \fBgetTRUNCATESIZE\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
gabriel 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
