.TH "Model.Individuals.CityTilesetPopulation" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Model.Individuals.CityTilesetPopulation
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBModel\&.Individuals\&.FixedSizePopulation< CityTileset >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCityTilesetPopulation\fP (long id, int maxSize)"
.br
.ti -1c
.RI "int \fBgetMaxParkValue\fP ()"
.br
.ti -1c
.RI "List< \fBCityTileset\fP > \fBsortPopulationByFitness\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBModel\&.Individuals\&.FixedSizePopulation< CityTileset >\fP
.in +1c
.ti -1c
.RI "\fBFixedSizePopulation\fP (long id, int maxSize)"
.br
.ti -1c
.RI "int \fBgetMaxSize\fP ()"
.br
.ti -1c
.RI "boolean \fBadd\fP (T individual)"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Attributes inherited from \fBModel\&.Individuals\&.FixedSizePopulation< CityTileset >\fP
.in +1c
.ti -1c
.RI "static final int \fBMAXSIZE\fP"
.br
.ti -1c
.RI "static final int \fBMINSIZE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
gabriel 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
