.TH "Model.fitness.PonderatedFunction" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Model.fitness.PonderatedFunction
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPonderatedFunction\fP (int moneyPoneration)"
.br
.ti -1c
.RI "void \fBevaluate\fP (CityTilesetPopulation pop)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
gabriel 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
