.TH "Model.fitness.ValueFunction" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Model.fitness.ValueFunction
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Double \fBEvaluate\fP (CityTileset city)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
gabriel 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
