.TH "Model.ParksInCityGA" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Model.ParksInCityGA
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParksInCityGA\fP (\fBCityParameters\fP cp, \fBModelParameters\fP mp)"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.ti -1c
.RI "CityTilesetPopulation \fBgetPopulation\fP ()"
.br
.ti -1c
.RI "void \fBapplyCrossover\fP ()"
.br
.ti -1c
.RI "void \fBapplyFitness\fP ()"
.br
.ti -1c
.RI "void \fBapplySelection\fP ()"
.br
.ti -1c
.RI "Population \fBsavePopulation\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
gabriel 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
