.TH "Model.Individuals.Tiles.Tile" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Model.Individuals.Tiles.Tile
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBModel\&.Individuals\&.Tiles\&.BuildingTile\fP, \fBModel\&.Individuals\&.Tiles\&.NullTile\fP, \fBModel\&.Individuals\&.Tiles\&.ParkTile\fP, \fBModel\&.Individuals\&.Tiles\&.RoadTile\fP, and \fBModel\&.Individuals\&.Tiles\&.VoidTile\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "abstract \fBTile\fP \fBmakeCopy\fP ()"
.br
.ti -1c
.RI "int \fBgetValue\fP ()"
.br
.ti -1c
.RI "abstract int \fBgetValue\fP (\fBTileType\fP type)"
.br
.ti -1c
.RI "boolean \fBisVoid\fP ()"
.br
.ti -1c
.RI "boolean \fBisBuilding\fP ()"
.br
.ti -1c
.RI "boolean \fBisPark\fP ()"
.br
.ti -1c
.RI "boolean \fBisRoad\fP ()"
.br
.ti -1c
.RI "boolean \fBcanBuild\fP ()"
.br
.ti -1c
.RI "abstract String \fBtoString\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBNOVALUETILE\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
gabriel 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
