.TH "Model.operators.crossover.CrossoverController" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Model.operators.crossover.CrossoverController
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCrossoverController\fP (\fBModelParameters\fP mp)"
.br
.ti -1c
.RI "Population< CityTileset > \fBapply\fP (CityTilesetPopulation pop)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBREPETITIONS\fP = 2"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
gabriel 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
