.TH "Model.Individuals.Tiles.TileType" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Model.Individuals.Tiles.TileType
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBUILDING\fP"
.br
.ti -1c
.RI "\fBPARK\fP"
.br
.ti -1c
.RI "\fBROAD\fP"
.br
.ti -1c
.RI "\fBVOID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
gabriel 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
