.TH "Model.Inicializer.InicializerController" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Model.Inicializer.InicializerController
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInicializerController\fP (\fBCityParameters\fP _cp, \fBModelParameters\fP _mp)"
.br
.ti -1c
.RI "CityTilesetPopulation \fBInicialize\fP ()"
.br
.ti -1c
.RI "CityTilesetPopulation \fBInicializeCities\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
gabriel 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
