.TH "Model.Individuals.Individual" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Model.Individuals.Individual
.SH SYNOPSIS
.br
.PP
.PP
Inherits Comparable< Individual >, and Cloneable\&.
.PP
Inherited by \fBModel\&.Individuals\&.CityTileset\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBgetFitness\fP ()"
.br
.ti -1c
.RI "void \fBsetFitness\fP (double fitness)"
.br
.ti -1c
.RI "int \fBcompareTo\fP (\fBIndividual\fP other)"
.br
.ti -1c
.RI "\fBIndividual\fP \fBclone\fP ()  throws CloneNotSupportedException "
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "double \fBfitness\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
