.TH "Model.operators.selection.KWayTournamentSelection" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Model.operators.selection.KWayTournamentSelection
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBapply\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
gabriel 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
