.TH "Model.Individuals.SortByfitness" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Model.Individuals.SortByfitness
.SH SYNOPSIS
.br
.PP
.PP
Inherits Comparator< Individual >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBcompare\fP (\fBIndividual\fP a, \fBIndividual\fP b)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
gabriel 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
