.TH "Model.Inicializer.RandomParkInicializer" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Model.Inicializer.RandomParkInicializer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRandomParkInicializer\fP (int spreadness)"
.br
.ti -1c
.RI "void \fBsetSpreadness\fP (int sp)"
.br
.ti -1c
.RI "void \fBInicialize\fP (CityTileset ct)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBmaxParks\fP"
.br
.ti -1c
.RI "int \fBminParks\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
gabriel 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
