.TH "Model.operators.crossover.NeighborhoodCrossover" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Model.operators.crossover.NeighborhoodCrossover
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBModel\&.operators\&.crossover\&.CrossoverOperator< CityTileset >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "CityTilesetPopulation \fBapply\fP (CityTilesetPopulation pop, Random generator)"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBModel\&.operators\&.crossover\&.CrossoverOperator< CityTileset >\fP
.in +1c
.ti -1c
.RI "ArrayList< Pairing > \fBmakeRandomPairings\fP (Population< T > population)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
gabriel 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
