.TH "Model.Individuals.Tiles.ParkTile" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Model.Individuals.Tiles.ParkTile
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBModel\&.Individuals\&.Tiles\&.Tile\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParkTile\fP (int v)"
.br
.ti -1c
.RI "\fBParkTile\fP \fBmakeCopy\fP ()"
.br
.ti -1c
.RI "void \fBsetValue\fP (int v)"
.br
.ti -1c
.RI "int \fBgetValue\fP (\fBTileType\fP type)"
.br
.ti -1c
.RI "void \fBaddValue\fP (int v)"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBModel\&.Individuals\&.Tiles\&.Tile\fP
.in +1c
.ti -1c
.RI "int \fBgetValue\fP ()"
.br
.ti -1c
.RI "boolean \fBisVoid\fP ()"
.br
.ti -1c
.RI "boolean \fBisBuilding\fP ()"
.br
.ti -1c
.RI "boolean \fBisPark\fP ()"
.br
.ti -1c
.RI "boolean \fBisRoad\fP ()"
.br
.ti -1c
.RI "boolean \fBcanBuild\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBgetAreaOfEffect\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Attributes inherited from \fBModel\&.Individuals\&.Tiles\&.Tile\fP
.in +1c
.ti -1c
.RI "static int \fBNOVALUETILE\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
gabriel 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBParkTile\fP Model\&.Individuals\&.Tiles\&.ParkTile\&.makeCopy ()"

.PP
Reimplemented from \fBModel\&.Individuals\&.Tiles\&.Tile\fP\&.
.SS "int Model\&.Individuals\&.Tiles\&.ParkTile\&.getValue (\fBTileType\fP type)"

.PP
Reimplemented from \fBModel\&.Individuals\&.Tiles\&.Tile\fP\&.
.SS "String Model\&.Individuals\&.Tiles\&.ParkTile\&.toString ()"

.PP
Reimplemented from \fBModel\&.Individuals\&.Tiles\&.Tile\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
