.TH "Model.CityParameters" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Model.CityParameters \- Class containing parameters for inizalitation of cities\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCityParameters\fP (int s, int rd, int bd, int ps, int pp)"
.br
.ti -1c
.RI "int \fBgetSize\fP ()"
.br
.ti -1c
.RI "int \fBgetRoadDensity\fP ()"
.br
.ti -1c
.RI "int \fBgetBuildingDensity\fP ()"
.br
.ti -1c
.RI "int \fBgetParkSpreadness\fP ()"
.br
.ti -1c
.RI "int \fBgetParksPercentage\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final int \fBDEFAULTSIZE\fP = 200"
.br
.RI "Default size for cities\&. "
.ti -1c
.RI "static final int \fBMINSIZE\fP = 10"
.br
.RI "Min size of a city\&. "
.ti -1c
.RI "static final int \fBMAXSIZE\fP = 400"
.br
.RI "Max Size of city\&. "
.ti -1c
.RI "static final int \fBNEIGHBORHOODSIZE\fP = 50"
.br
.ti -1c
.RI "static final int \fBMAXSCHOOLSPERTILES\fP = 30"
.br
.ti -1c
.RI "static final int \fBDEFSCHOOLSPERTILES\fP = 10"
.br
.ti -1c
.RI "static final int \fBMINSCHOOLSPERTILES\fP = 1"
.br
.ti -1c
.RI "static int \fBMINPERCENTAGEOFPARKS\fP"
.br
.ti -1c
.RI "static int \fBMAXPERCENTAGEOFPARKS\fP"
.br
.ti -1c
.RI "static final int \fBPERCENTAGERANGE\fP = 1"
.br
.ti -1c
.RI "static final int \fBDEFPARKSPARCENTAGE\fP = 7"
.br
.ti -1c
.RI "static final int \fBMINSEPARATIONOFROADS\fP = 4"
.br
.ti -1c
.RI "static final int \fBMINROADDENSITY\fP = 1"
.br
.ti -1c
.RI "static final int \fBDEFROADDENSITY\fP = 20"
.br
.ti -1c
.RI "static final int \fBMAXROADDENSITY\fP = 50"
.br
.ti -1c
.RI "static final int \fBMINBUILDINGDENSITY\fP = 10"
.br
.ti -1c
.RI "static final int \fBDEFBUILDINGDENSITY\fP = 70"
.br
.ti -1c
.RI "static final int \fBMAXBUILDINGDENSITY\fP = 100"
.br
.ti -1c
.RI "static final int \fBMAXBUILDINGSIZE\fP = MINSEPARATIONOFROADS * 2"
.br
.ti -1c
.RI "static final int \fBMINBUILDINGSIZE\fP = MINSEPARATIONOFROADS / 2"
.br
.ti -1c
.RI "static int \fBDEFPARKSPREADNESS\fP = 1"
.br
.ti -1c
.RI "static int \fBMAXPARKSPREADNESS\fP = 1000"
.br
.ti -1c
.RI "static int \fBMINPARKSPREADNESS\fP = 1"
.br
.ti -1c
.RI "static int \fBSTOPTRYSPAND\fP = 100"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class containing parameters for inizalitation of cities\&. 


.PP
\fBAuthor\fP
.RS 4
gabriel 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "Model\&.CityParameters\&.CityParameters (int s, int rd, int bd, int ps, int pp)"
Constructor 
.PP
\fBParameters\fP
.RS 4
\fIs\fP Size of the city 
.br
\fIrd\fP Road density 
.br
\fIbd\fP Building density 
.br
\fIps\fP Parks spreadness\&. The less spreadness, the bigger the parks 
.br
\fIpp\fP Parks percentage 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "int Model\&.CityParameters\&.getSize ()"
Getter of size 
.PP
\fBReturns\fP
.RS 4
Size of cities 
.RE
.PP

.SS "int Model\&.CityParameters\&.getRoadDensity ()"
Getter of road density 
.PP
\fBReturns\fP
.RS 4
Road density 
.RE
.PP

.SS "int Model\&.CityParameters\&.getBuildingDensity ()"
Getter of building density 
.PP
\fBReturns\fP
.RS 4
Building density 
.RE
.PP

.SS "int Model\&.CityParameters\&.getParkSpreadness ()"
Getter of park spreadness 
.PP
\fBReturns\fP
.RS 4
Park spreadness 
.RE
.PP

.SS "int Model\&.CityParameters\&.getParksPercentage ()"
Getter of parks percentage 
.PP
\fBReturns\fP
.RS 4
Parks percentage 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "final int Model\&.CityParameters\&.MAXSCHOOLSPERTILES = 30\fC [static]\fP"
<Size of the neighborhoods\&. It works better if it divides SETSIZE 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
