.TH "Model.Individuals.Neighborhood" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Model.Individuals.Neighborhood
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final int \fBDEFAULTMAXPARKS\fP = Integer\&.MAX_VALUE"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBNeighborhood\fP (int _maxParks, int _size)"
.br
.ti -1c
.RI "\fBNeighborhood\fP (\fBNeighborhood\fP cp)"
.br
.ti -1c
.RI "int \fBgetTotalValue\fP ()"
.br
.ti -1c
.RI "void \fBsetTotalValue\fP (int tv)"
.br
.ti -1c
.RI "void \fBsetNParks\fP (int nparks)"
.br
.ti -1c
.RI "int \fBgetNParks\fP ()"
.br
.ti -1c
.RI "int \fBgetSize\fP ()"
.br
.ti -1c
.RI "boolean \fBaddPark\fP (ParkTile p)"
.br
.ti -1c
.RI "boolean \fBcanAddPark\fP ()"
.br
.ti -1c
.RI "boolean \fBdeletePark\fP (ParkTile p)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
gabriel 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
