.TH "Model.Individuals.Population< T extends Individual >" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Model.Individuals.Population< T extends Individual >
.SH SYNOPSIS
.br
.PP
.PP
Inherits HashSet< T >, and Comparable< Population< T > >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPopulation\fP (long id)"
.br
.ti -1c
.RI "\fBPopulation\fP (\fBPopulation\fP p)"
.br
.ti -1c
.RI "long \fBgetId\fP ()"
.br
.ti -1c
.RI "void \fBsetId\fP (long id)"
.br
.ti -1c
.RI "T \fBgetBestIndividual\fP ()"
.br
.ti -1c
.RI "void \fBsetBestIndividual\fP (T bestIndividual)"
.br
.ti -1c
.RI "double \fBgetAverageFitness\fP ()"
.br
.ti -1c
.RI "ArrayList< T > \fBgetArrayList\fP ()"
.br
.ti -1c
.RI "int \fBcompareTo\fP (\fBPopulation\fP other)"
.br
.ti -1c
.RI "\fBPopulation\fP< T > \fBclone\fP ()"
.br
.ti -1c
.RI "boolean \fBequals\fP (Object o)"
.br
.ti -1c
.RI "int \fBhashCode\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
