.TH "Model.Inicializer.RandomCityInicializer" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Model.Inicializer.RandomCityInicializer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetCt\fP (CityTileset _ct)"
.br
.ti -1c
.RI "void \fBsetNewBuildingProb\fP (double nbp)"
.br
.ti -1c
.RI "void \fBinicialize\fP (CityTileset _ct, int n_nodes)"
.br
.ti -1c
.RI "void \fBgenerateNodes\fP (int n_nodes)"
.br
.ti -1c
.RI "void \fBcreateBuildings\fP ()"
.br
.ti -1c
.RI "void \fBcreateBuildings\fP (int n_buildings, boolean type)"
.br
.ti -1c
.RI "void \fBcreateRoads\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
gabriel 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
