.TH "parksincity_geneticalgorithms.ParksInCity_GeneticAlgorithms" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
parksincity_geneticalgorithms.ParksInCity_GeneticAlgorithms
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
gabriel 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static void parksincity_geneticalgorithms\&.ParksInCity_GeneticAlgorithms\&.main (String[] args)\fC [inline]\fP, \fC [static]\fP"

.PP
\fBParameters\fP
.RS 4
\fIargs\fP the command line arguments 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
