.TH "Views.View" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Views.View
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBViews\&.GUI\&.MainWindow\fP, and \fBViews\&.GUI\&.StartView\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBupdateView\fP ()"
.br
.ti -1c
.RI "void \fBshowView\fP ()"
.br
.ti -1c
.RI "String \fBgetAppName\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Profe 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
