.TH "Views.GUI.ModelParametersVIew" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Views.GUI.ModelParametersVIew
.SH SYNOPSIS
.br
.PP
.PP
Inherits javax\&.swing\&.JPanel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBModelParametersVIew\fP ()"
.br
.ti -1c
.RI "int \fBgetPopSizeValue\fP ()"
.br
.ti -1c
.RI "int \fBgetMoneyPonderationValue\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
gabriel 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "Views\&.GUI\&.ModelParametersVIew\&.ModelParametersVIew ()\fC [inline]\fP"
Creates new form ModelParametersVIew 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
