.TH "Views.GUI.CityView" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Views.GUI.CityView
.SH SYNOPSIS
.br
.PP
.PP
Inherits javax\&.swing\&.JPanel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "CityTileset \fBgetCt\fP ()"
.br
.ti -1c
.RI "BufferedImage \fBcreateCityImage\fP (CityTileset ct, int aumFactor)"
.br
.ti -1c
.RI "BufferedImage \fBcreateCityImage\fP (CityTileset ct)"
.br
.ti -1c
.RI "void \fBupdateView\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
gabriel 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
