.TH "Views.GUI.SlideBar" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Views.GUI.SlideBar
.SH SYNOPSIS
.br
.PP
.PP
Inherits javax\&.swing\&.JPanel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSlideBar\fP ()"
.br
.ti -1c
.RI "void \fBsetLimits\fP (int max, int min)"
.br
.ti -1c
.RI "void \fBsetDefault\fP (int def)"
.br
.ti -1c
.RI "int \fBgetValue\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
gabriel 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "Views\&.GUI\&.SlideBar\&.SlideBar ()\fC [inline]\fP"
Creates new form prueba 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
