.TH "Views.GUI.CityParametersView" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Views.GUI.CityParametersView
.SH SYNOPSIS
.br
.PP
.PP
Inherits javax\&.swing\&.JPanel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCityParametersView\fP ()"
.br
.ti -1c
.RI "int \fBgetCitySizeValue\fP ()"
.br
.ti -1c
.RI "int \fBgetRoadDensity\fP ()"
.br
.ti -1c
.RI "int \fBgetBuildingDensity\fP ()"
.br
.ti -1c
.RI "int \fBgetParkSpreadness\fP ()"
.br
.ti -1c
.RI "int \fBgetParksPercentage\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
gabriel 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "Views\&.GUI\&.CityParametersView\&.CityParametersView ()"
Creates new form CityParametersView 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
