.TH "Views.GUI.MainWindow" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Views.GUI.MainWindow
.SH SYNOPSIS
.br
.PP
.PP
Inherits javax\&.swing\&.JFrame, and \fBViews\&.View\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBupdateView\fP ()"
.br
.ti -1c
.RI "void \fBsetPopulationCT\fP (Population< CityTileset > p)"
.br
.ti -1c
.RI "void \fBshowView\fP ()"
.br
.ti -1c
.RI "String \fBgetAppName\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
gabriel 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "String Views\&.GUI\&.MainWindow\&.getAppName ()\fC [inline]\fP"

.PP
Implements \fBViews\&.View\fP\&.
.SS "void Views\&.GUI\&.MainWindow\&.showView ()\fC [inline]\fP"

.PP
Implements \fBViews\&.View\fP\&.
.SS "void Views\&.GUI\&.MainWindow\&.updateView ()\fC [inline]\fP"

.PP
Implements \fBViews\&.View\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
