.TH "Views.GUI.StartView" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Views.GUI.StartView
.SH SYNOPSIS
.br
.PP
.PP
Inherits javax\&.swing\&.JFrame, and \fBViews\&.View\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStartView\fP ()"
.br
.ti -1c
.RI "\fBMainWindow\fP \fBgenerateMainWindow\fP ()"
.br
.ti -1c
.RI "void \fBupdateView\fP ()"
.br
.ti -1c
.RI "void \fBshowView\fP ()"
.br
.ti -1c
.RI "String \fBgetAppName\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
gabriel 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "Views\&.GUI\&.StartView\&.StartView ()"
Creates new form StartView 
.SH "Member Function Documentation"
.PP 
.SS "void Views\&.GUI\&.StartView\&.updateView ()"

.PP
Implements \fBViews\&.View\fP\&.
.SS "void Views\&.GUI\&.StartView\&.showView ()"

.PP
Implements \fBViews\&.View\fP\&.
.SS "String Views\&.GUI\&.StartView\&.getAppName ()"

.PP
Implements \fBViews\&.View\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
