/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.GUI;

import Model.Individuals.CityTileset;
import Model.Individuals.Tiles.*;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import Views.View;

/**
 *
 * @author gabriel
 */
public class CityView extends javax.swing.JPanel{
    static int PIXELSIZE = 4;
    static final int MAXPIXELSIZE = 20;
    static final int MINPIXELSIZE = 1;
    
    CityTileset ct;
            
    CityView(CityTileset _ct){
        ct = _ct;
        
        initComponents();
        
        cityShow_label.setIcon(new ImageIcon(createCityImage(ct)));
    }
    
    public BufferedImage createCityImage(CityTileset ct, int aumFactor){
        
        int ctSize = ct.getSize();
        int newPxlSize = CityView.PIXELSIZE*aumFactor;
        
        BufferedImage ctImg = new BufferedImage
        (ctSize*newPxlSize,ctSize*newPxlSize, BufferedImage.TYPE_INT_RGB);
        
        Graphics2D g = (Graphics2D) ctImg.getGraphics();
        g.setStroke(new BasicStroke(newPxlSize));
        
        for(int i = 0; i < ctSize; ++i){
            for(int j = 0; j < ctSize; ++j){
                g.setColor(getTileColor(ct.getTile(i, j)));
                g.drawRect(i*newPxlSize, j*newPxlSize, 0, 0);
            }
        }
        
        return ctImg;
    }
    
    public BufferedImage createCityImage(CityTileset ct){
        return createCityImage(ct,1);
    }
    
        
    private Color getTileColor(Tile tl){
        Color clr = Color.white;
        if(tl.isVoid()){
            clr = Color.WHITE;
        }else if(tl.isPark()){
            clr = Color.GREEN;
        }else if(tl.isRoad()){
            clr = Color.BLACK;
        }else if(tl.isBuilding()){
            clr = new Color(200*tl.getValue(TileType.BUILDING)/BuildingTile.MAXCITIZEN,0,0);
        }
        
        return clr;
    }
    
    public void updateView(){
        cityShow_label.setIcon(new ImageIcon(createCityImage(ct)));
        System.out.print(PIXELSIZE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cityShow_label = new javax.swing.JLabel();

        cityShow_label.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cityShow_label, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cityShow_label, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cityShow_label;
    // End of variables declaration//GEN-END:variables
}
