/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views.GUI;

import Model.Individuals.CityTileset;
import Model.Individuals.Population;
import Model.Individuals.Individual;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JFrame;


/**
 *
 * @author gabriel
 */
public class MainWindow extends javax.swing.JFrame {

    private static MainWindow instance = null;
    private String appName = "NeigborhoodParkGA";
    
    ArrayList<cityView> actualPopulation;
    
    public static MainWindow getInstance () {
      if (instance == null) {
        instance = new MainWindow();
      }
      return instance;
    }
    
    private MainWindow() {
        setTitle(appName); //Add the title to frame
        setLayout(null); //Terminates default flow layout
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); //Terminate program on close button
        setBounds(100, 200, 600, 600); //Sets the position of the frame
        
        actualPopulation = new ArrayList<>();
        
        initComponents();
    }

    public void updateView(){
        repaint();
        revalidate();
    }
    
    public void setPopulationCT(Population<CityTileset> p){
        
        System.out.print(p.size());
        
        for(CityTileset i: p){
           IndividualSelector.addItem(Integer.toString(i.getId()));
           
           actualPopulation.add(new cityView(i));
        }
    }
    
    public void showView() {
        setVisible(true);
    }
    
    public String getAppName(){
        return appName;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IndividualShow_scroll = new javax.swing.JScrollPane();
        IndividualShow_panel = new javax.swing.JPanel();
        IndividualSelector = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(100, 100));

        IndividualShow_scroll.setMinimumSize(new java.awt.Dimension(100, 100));

        IndividualShow_panel.setAutoscrolls(true);
        IndividualShow_panel.setMinimumSize(new java.awt.Dimension(100, 100));
        IndividualShow_scroll.setViewportView(IndividualShow_panel);

        IndividualSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default" }));
        IndividualSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IndividualSelectorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IndividualSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(312, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(IndividualShow_scroll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IndividualSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IndividualShow_scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IndividualSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IndividualSelectorActionPerformed
        // TODO add your handling code here:
        IndividualShow_panel.removeAll();
        IndividualShow_panel.add(actualPopulation.get(IndividualSelector.getSelectedIndex()));
        
        updateView();
    }//GEN-LAST:event_IndividualSelectorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> IndividualSelector;
    private javax.swing.JPanel IndividualShow_panel;
    private javax.swing.JScrollPane IndividualShow_scroll;
    // End of variables declaration//GEN-END:variables
}
