/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views.GUI;

import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.ImageIcon;


import Views.View;
import java.awt.image.BufferedImage;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.BasicStroke;

import Individuals.CityTileset;
import Individuals.Tiles.*;

/**
 *
 * @author gabriel
 */
public class MainWindow extends javax.swing.JFrame implements View {
    private static MainWindow instance = null;
    private String appName;

    public static MainWindow getInstance () {
      if (instance == null) {
        instance = new MainWindow();
      }
      return instance;
    }
    
    private MainWindow() {
        initComponents();
        appName = "Tutorial GUI 1.0";
        setTitle (appName);
        repaint();
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        /*addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                Controller.getInstance().finish(0);
            }
        });*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void updateView(){
        //createCityImage();
    }
    
    public BufferedImage createCityImage(CityTileset ct){
        
        int ctSize = ct.getSize();
        
        BufferedImage ctImg = new BufferedImage(ctSize,ctSize, BufferedImage.TYPE_INT_RGB);
        
        Graphics2D g = (Graphics2D) ctImg.getGraphics();
        g.setStroke(new BasicStroke(1));
        
        for(int i = 0; i < ctSize; ++i){
            for(int j = 0; j < ctSize; ++j){
                g.setColor(getTileColor(ct.getTile(i, j)));
                g.drawRect(i, j, 0, 0);
            }
        }
        
        jLabel1.setIcon(new ImageIcon(ctImg));
        return ctImg;
    }
    
    private Color getTileColor(Tile tl){
        Color clr = Color.white;
        if(tl.getValue(TileType.VOID) != Tile.NOVALUETILE){
            clr = Color.WHITE;
        }else if(tl.getValue(TileType.PARK) != Tile.NOVALUETILE){
            clr = Color.GREEN;
        }else if(tl.getValue(TileType.ROAD) != Tile.NOVALUETILE){
            clr = Color.BLACK;
        }else if(tl.getValue(TileType.BUILDING) != Tile.NOVALUETILE){
            clr = Color.GRAY;
        }
        
        return clr;
    }
    
    public void showView() {
        setVisible(true);
    }
    
    public String getAppName(){
        return appName;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
