package Views.GUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import Model.Individuals.FixedSizePopulation;
import Model.ModelParameters;

/**
 *
 * @author gabriel
 */
public class ModelParametersVIew extends javax.swing.JPanel {

    /**
     * Creates new form ModelParametersVIew
     */
    public ModelParametersVIew() {
        initComponents();
        slideBar1.setLimits(FixedSizePopulation.MAXSIZE,
                FixedSizePopulation.MINSIZE);
        slideBar2.setLimits(100, 0);
        slideBar2.setDefault(50);
        slideBar3.setLimits(ModelParameters.MAXREPETITIONLIMIT, 
                ModelParameters.MINREPETITIONLIMIT);
        slideBar3.setDefault(ModelParameters.DEFREPETITIONLIMIT);
    }
    
    public int getPopSizeValue(){
        return slideBar1.getValue();
    }
    
    public int getMoneyPonderationValue(){
        return slideBar2.getValue();
    }
    
    public int getRepetitions(){
        return slideBar3.getValue();
    }
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        slideBar1 = new Views.GUI.SlideBar();
        PopSizeLabel1 = new javax.swing.JLabel();
        slideBar2 = new Views.GUI.SlideBar();
        PopSizeLabel2 = new javax.swing.JLabel();
        slideBar3 = new Views.GUI.SlideBar();
        PopSizeLabel3 = new javax.swing.JLabel();

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        PopSizeLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        PopSizeLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PopSizeLabel1.setText("Population Size");

        PopSizeLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        PopSizeLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PopSizeLabel2.setText("Repetitions");

        PopSizeLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        PopSizeLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PopSizeLabel3.setText("Money ponderation");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PopSizeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PopSizeLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PopSizeLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slideBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                    .addComponent(slideBar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                    .addComponent(slideBar3, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(PopSizeLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(slideBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(slideBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(slideBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(PopSizeLabel3)
                                .addGap(29, 29, 29)
                                .addComponent(PopSizeLabel2)))
                        .addGap(0, 272, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PopSizeLabel1;
    private javax.swing.JLabel PopSizeLabel2;
    private javax.swing.JLabel PopSizeLabel3;
    private javax.swing.JSeparator jSeparator1;
    private Views.GUI.SlideBar slideBar1;
    private Views.GUI.SlideBar slideBar2;
    private Views.GUI.SlideBar slideBar3;
    // End of variables declaration//GEN-END:variables
}
