/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.GUI;

import Model.Individuals.CityTileset;
import Model.Individuals.FixedSizePopulation;

/**
 *
 * @author gabriel
 */
public class ModelParametersVIew extends javax.swing.JPanel {

    /**
     * Creates new form ModelParametersVIew
     */
    public ModelParametersVIew() {
        initComponents();
        slideBar1.setLimits(FixedSizePopulation.MAXSIZE,FixedSizePopulation.MINSIZE);
        CitySlide.setLimits(CityTileset.MAXSIZE, CityTileset.MINSIZE);
        CitySlide.setDefault(CityTileset.DEFAULTSIZE);
        
    }
    
    public int getPopSizeValue(){
        return slideBar1.getValue();
    }
    
    public int getCitySizeValue(){
        return CitySlide.getValue();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CitySizeLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        slideBar1 = new Views.GUI.SlideBar();
        PopSizeLabel1 = new javax.swing.JLabel();
        CitySlide = new Views.GUI.SlideBar();

        CitySizeLabel.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        CitySizeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CitySizeLabel.setText("City Size");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        PopSizeLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        PopSizeLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PopSizeLabel1.setText("Population Size");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PopSizeLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                    .addComponent(CitySizeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CitySlide, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                    .addComponent(slideBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PopSizeLabel1)
                        .addGap(29, 29, 29)
                        .addComponent(CitySizeLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(slideBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CitySlide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(179, 367, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CitySizeLabel;
    private Views.GUI.SlideBar CitySlide;
    private javax.swing.JLabel PopSizeLabel1;
    private javax.swing.JSeparator jSeparator1;
    private Views.GUI.SlideBar slideBar1;
    // End of variables declaration//GEN-END:variables
}
