/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views.GUI;

import Basics.Position;
import Model.Individuals.CityTileset;
import Model.Individuals.FixedSizePopulation;
import Model.Inicializer.RandomCityInicializer;
import Views.View;
import javax.swing.JFrame;

/**
 *
 * @author gabriel
 */
public class StartView extends javax.swing.JFrame implements View{
    
    private String appName = "NeigborhoodParkGA";

    /**
     * Creates new form StartView
     */
    public StartView() {
        setTitle(getAppName()); //Add the title to frame
        setLayout(null); //Terminates default flow layout
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); //Terminate program on close button
        setBounds(100, 200, 600, 600); //Sets the position of the frame

        showView();

        initComponents();
    }

    //Test
    public MainWindow generateMainWindow(){
        CityTileset ct = new CityTileset(modelParametersVIew1.getCitySizeValue());
        FixedSizePopulation<CityTileset> ctPop = new FixedSizePopulation<>(1,modelParametersVIew1.getPopSizeValue());
                        
        RandomCityInicializer generator = 
                new RandomCityInicializer(ct,300);
        generator.createRoads();
        generator.createBuildings(300, true);
        generator.createBuildings(300, false);

        for(int i = 0; i < modelParametersVIew1.getPopSizeValue(); ++i){
            
            if(i >= 3){
                 ct.NewParkTile(new Position(i,i));
            }
            ctPop.add(new CityTileset(ct));
            
        }
        
        MainWindow gui = MainWindow.getInstance();
        //gui.setIcon(ct);
        gui.setPopulationCT(ctPop);
        
        return gui;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        modelParametersVIew1 = new Views.GUI.ModelParametersVIew();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Parks in the city");

        startButton.setText("START");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(modelParametersVIew1, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(modelParametersVIew1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        generateMainWindow().showView();
    }//GEN-LAST:event_startButtonActionPerformed

  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private Views.GUI.ModelParametersVIew modelParametersVIew1;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateView() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void showView() {
        setVisible(true);
    }

    @Override
    public String getAppName() {
        return appName;
    }
}
